export const COLOR_PALETTE = {
  ACCENT_COLOR: '#ffc11c',
  BLACK: '#222',
  CAUTION_COLOR: '#dcf0ff',
  DARK_GRAY: '#a6a6a6',
  ERROR_COLOR: '#ff1d1c',
  FAVORITE_ON: '#ff7683',
  GRAY: '#e4e4e4',
  LIGHT_GRAY: '#f4f4f4',
  MAIN_COLOR: '#1ba1ff',
  SPEAR_GRAY: '#4d4d4d',
  SUB_COLOR: '#1c5db5',
  SUCCESS_COLOR: '#0d8116',
  SUCCESS_SUB_COLOR: '#ddebd7',
  WARNING_COLOR: '#fff4f4',
  WHITE: '#fff',
  MODAL_BACKGROUND_COLOR: 'rgba(0, 0, 0, 0.8)',
} as const;
