version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.7
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: heroku-admin-secret
      # HASURA_GRAPHQL_JWT_SECRET:
      #   {
      #     'type': 'RS512',
      #     'key': "-----BEGIN CERTIFICATE-----\nMIIDDTCCAfWgAwIBAgIJF2yEi1/IFHpVMA0GCSqGSIb3DQEBCwUAMCQxIjAgBgNV\nBAMTGWRldi1kdDhwOXJvMi51cy5hdXRoMC5jb20wHhcNMjEwODI4MjMyNzQ0WhcN\nMzUwNTA3MjMyNzQ0WjAkMSIwIAYDVQQDExlkZXYtZHQ4cDlybzIudXMuYXV0aDAu\nY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4PY2jbb7beBlcDQU\ne43qJsc7UoorxFNQXZKnKdw+NThwogM7/u5rE8lR2Naa8aeYNJJd6jJmCPqe7pfI\n0ozZt7Tu3ipA1WcWnFh5AcpNXiiXorZaE+s2ddEJc8w2zcqw8MyaznRpxEOmq7bE\nyScFD+QYqIqV3vcK2wlmESJZ1YUQgzcXpzzF6Dv0x2ChDqjr3Oophx/dXELUcxpS\n52TskSmpf6uiX8fEXdC1+pdnB5NQdZwji5fpVucqQ/CZbwxrj6ymRrmj2B9SOfCa\n8hGPoTf8tTaB13eepj+QJvWb56eGW+iugZkvsJy04DAyX7uMko7Nj8vP1lakCc5/\nbpgK7QIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBT1xb3hVIAz\nxZXLepEJHOd0aszygTAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEB\nADXRa9S3lrn+EZ8zavjMLIX2AYf8c7eLz+3E9u8q9zJJXFPchLr9RHub/qSeufx0\n5yEHzmXbIt1BLOAJs/kOfLIEJSLr7DkZExOHu8vqgjambdL76Nc4x9zTTiryhI3P\nvBuiWXpDNfukv3xLf2CHV1nezDFtE5U+tVrxWdxD/YdUzulPep7bTlFmZE34WZRS\nmcHpdQs1tuUDl1Iy3RFbwyZxxp1epMVEAYW5J1oE4g4x/ZDS8NMp4f7GIMT1c5qF\n8S8+jR+c6mPwpiwdagF5lg97GGRt+Bm5CVAksx7tQdrgqXh1X0qtqPcHouTaIzAm\n7Yyk5a8+jj869Hfkj9HmefY=\n-----END CERTIFICATE-----",
      #   }
volumes:
  db_data:
