name: Node.js CI

on: ["push"]

jobs:
  client-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node: [16.x]

    steps:
      - name: Setup NodeJs ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Client Yarn Install
        # キャッシュすると GitHub Actions が落ちるのでいったんコメントアウト
        # if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn client install

      - name: Client Prettier Test
        run: yarn client prettier-ci-test

      - name: Client ESLint
        run: yarn client lint:cache

      - name: Client Type Check
        run: yarn client ts-test

      - name: Client Unit Test & DOM Test
        run: yarn client jest

      - name: Client Next Build
        run: yarn client build

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
