name: Storybook Deploy

# プッシュもしくはマージでワークフローをトリガーする
# ただし、masterブランチの場合のみ
on:
  push:
    branches:
      - "master"

jobs:
  storybook-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node: [14.x]

    steps:
      - name: Setup NodeJs ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Yarn Install
        # if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn client install

      - name: build storybook
        run: yarn client build-storybook

      - name: deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: packages/client/build
